name: Supabase Database Branching Preview
author: 0xbigboss
description: Waits for a Supabase database branch to be ready and returns the database connection details.
branding:
  color: green
  icon: database
inputs:
  supabase-access-token:
    description: The Supabase Access Token with experimental features enabled.
    required: true
  supabase-project-id:
    description: The Supabase Project ID with database branching enabled.
    required: true
  wait-for-migrations:
    description: Whether to wait for migrations to be applied before returning the branch.
    default: "false"
    required: false
  timeout:
    description: The maximum time in seconds to wait for the branch to be ready.
    default: "60"
    required: false
outputs:
  id:
    description: The ID of the branch in Supabase.
  name:
    description: The name of the branch in Supabase.
  project_ref:
    description: The project reference ID of the branch in Supabase.
  parent_project_ref:
    description: The parent project ID of the branch in Supabase.
  git_branch:
    description: The git branch of the branch in Supabase.
  pr_number:
    description: The pull request number of the branch in Supabase.
  reset_on_push:
    description: Whether the branch is reset on push.
  branch_status:
    description: The status of the branch in Supabase.
  created_at:
    description: The creation date of the branch in Supabase.
  updated_at:
    description: The last update date of the branch in Supabase.
  api_url:
    description: The API URL of the branch.
  graphql_url:
    description: The GraphQL URL of the branch.
  db_host:
    description: The DB host of the branch.
  db_port:
    description: The DB port of the branch.
  db_user:
    description: The DB user of the branch.
  db_pass:
    description: The DB password of the branch.
  jwt_secret:
    description: The JWT secret of the branch.
runs:
  using: node20
  main: dist/index.js
